# Generated by Django 3.1.3 on 2020-12-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellBeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fatigueScale', models.IntegerField()),
                ('painScale', models.IntegerField()),
                ('symptoms', models.CharField(choices=[('none', 'headache'), ('nausea', 'vertigo'), ('blurred vison', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='none', max_length=30)),
                ('hoursOfSleep', models.IntegerField()),
                ('emotionalWellBeing', models.CharField(max_length=50)),
            ],
        ),
    ]
