# Generated by Django 3.1.3 on 2021-01-05 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='none', max_length=200)),
                ('link', models.CharField(default='none', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DaysSinceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellBeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fatigueScale', models.IntegerField()),
                ('painScale', models.IntegerField()),
                ('noSymptoms', models.BooleanField(default='false')),
                ('numbness', models.BooleanField(default='false')),
                ('tingling', models.BooleanField(default='false')),
                ('weakness', models.BooleanField(default='false')),
                ('stiffness', models.BooleanField(default='false')),
                ('coordinationOrBalanceProblems', models.BooleanField(default='false')),
                ('heatSensitivity', models.BooleanField(default='false')),
                ('incontenance', models.BooleanField(default='false')),
                ('brainFog', models.BooleanField(default='false')),
                ('hoursOfSleep', models.IntegerField()),
                ('emotionalWellBeing', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.CharField(default='none', max_length=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal_name', models.CharField(default='none', max_length=200)),
                ('goal_length', models.CharField(default='none', max_length=200)),
                ('goal_reason', models.CharField(default='none', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.CreateModel(
            name='DaysSinceBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daysSinceBoard', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='none', max_length=10000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.CreateModel(
            name='CheckedGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checked', models.BooleanField(default='false')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.goals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayssinceapi.dayssinceuser'),
        ),
    ]
