# Generated by Django 3.1.3 on 2020-12-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayssinceapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellbeing',
            name='brainFog',
        ),
        migrations.RemoveField(
            model_name='wellbeing',
            name='coordinationOrBalanceProblems',
        ),
        migrations.RemoveField(
            model_name='wellbeing',
            name='heatSensitivity',
        ),
        migrations.RemoveField(
            model_name='wellbeing',
            name='incontenance',
        ),
        migrations.RemoveField(
            model_name='wellbeing',
            name='stiffness',
        ),
        migrations.RemoveField(
            model_name='wellbeing',
            name='weakness',
        ),
    ]
