# Generated by Django 3.1.3 on 2020-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayssinceapi', '0002_dayssinceuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayssinceuser',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='dayssinceuser',
            name='firstName',
        ),
    ]
