# Generated by Django 3.1.3 on 2020-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayssinceapi', '0003_auto_20201205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellbeing',
            name='emotionalWellBeing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wellbeing',
            name='symptoms',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
