# Generated by Django 3.1.3 on 2020-12-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayssinceapi', '0004_auto_20201206_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.CharField(default='none', max_length=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry', to='dayssinceapi.dayssinceuser')),
            ],
        ),
    ]
